language: ruby
rvm:
- 2.2.0

install:
  # Install the latests version of rainforest-cli. This will allow us to
  # trigger a Rainforest run after each deploy.
  - gem install rainforest-cli
  - bundle install

deploy:
  # Deploy to our staging environment on Heroku
  - provider: heroku
    api_key:
      secure: gGZwXnv/+n5J1qRzcbm8hQZxg9eToNPKNm0Vjs2S05kVzq67sPZD0MlfzUyx1ejqZTS7FWxkTWspAs3QTgJC7HsTXGY0qIenK/m9KkUKMpEgd35hMBLJx516kQgO1GAFkJSYp/AvIVN6krqs0Z96U0eshKdmWdINO6PTa95QLds=
    app: rainforest-ci-sample-staging
    on:
      repo: rainforestapp/ci-sample
      branch: develop
    # Run a script after the deploy. This starts Rainforest and pushes to master
    run: "./bin/rainforest_cd"

  # Deploy to our production environment on Heroku
  - provider: heroku
    api_key:
      secure: gGZwXnv/+n5J1qRzcbm8hQZxg9eToNPKNm0Vjs2S05kVzq67sPZD0MlfzUyx1ejqZTS7FWxkTWspAs3QTgJC7HsTXGY0qIenK/m9KkUKMpEgd35hMBLJx516kQgO1GAFkJSYp/AvIVN6krqs0Z96U0eshKdmWdINO6PTa95QLds=
    app: rainforest-ci-sample-prd
    on:
      repo: rainforestapp/ci-sample
      branch: master

