language: ruby
rvm:
- 2.2.0

install:
  # Install the latests version of rainforest-cli. This will allow us to
  # trigger a Rainforest run after each deploy.
  - gem install rainforest-cli
  - bundle install

deploy:
  # Deploy to our staging environment on Heroku
  - provider: heroku
    api_key:
      secure: gGZwXnv/+n5J1qRzcbm8hQZxg9eToNPKNm0Vjs2S05kVzq67sPZD0MlfzUyx1ejqZTS7FWxkTWspAs3QTgJC7HsTXGY0qIenK/m9KkUKMpEgd35hMBLJx516kQgO1GAFkJSYp/AvIVN6krqs0Z96U0eshKdmWdINO6PTa95QLds=
    app: rainforest-ci-sample-staging
    on:
      repo: rainforestapp/ci-sample
      branch: develop
    run:
      # Run all Rainforest tests. RAINFOREST_TOKEN is an environment variable
      # that needs to be configued in CircleCI's UI. It represents the API token
      # of your Rainforest account. You can find it in your account's settings.
      - rainforest run all --token $RAINFOREST_TOKEN --fg --fail-fast

      # Our Rainforest build was successul! Push the code to the master branch
      # which will kick another circle build deploying our code to production.
      - git push origin $CIRCLE_SHA1:refs/heads/master

  # Deploy to our production environment on Heroku
  - provider: heroku
    api_key:
      secure: gGZwXnv/+n5J1qRzcbm8hQZxg9eToNPKNm0Vjs2S05kVzq67sPZD0MlfzUyx1ejqZTS7FWxkTWspAs3QTgJC7HsTXGY0qIenK/m9KkUKMpEgd35hMBLJx516kQgO1GAFkJSYp/AvIVN6krqs0Z96U0eshKdmWdINO6PTa95QLds=
    app: rainforest-ci-sample-prd
    on:
      repo: rainforestapp/ci-sample
      branch: master

